---
apiVersion: v1
kind: Secret
metadata:
  name: vector-ares-ingest-aws
  namespace: observability
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6Ex2Ew3YMwr898XEsPyLgcAafZE=,iv:XZTny5cFCTb6fUE5as+qYp92C+bQIfKfs77buIPO18c=,tag:BZ3aeVIhkx9jEO6TkGwMpQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fdCIIU6jZZ2qCdwxCGpl1J2Y70wuwuDLq0BQI3LFEptNEK1C7OK8QA==,iv:sUjBdvZ6XhX+B4ssGirlnNGzM22q2HwRN4beF5J/gm0=,tag:y4iYuhlf/tULIdH+Vveb1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1akxZanJOY2JqcnRUQVRR
        WUw2M0RJcmVRSVBYOXlRckMyQkNSRGVXWEVBCnRQSnBvelZjVU4zNmJuNzZRWUxj
        OUpCcjVhYVhzRFN1UzBSL1RhQjFTblUKLS0tIC9aL0o4N2NwSFUzd1VYeVo1Z0hJ
        RnEzUFY0MEN2ZnhRV09GUVZHOXZrWkkKMEtbthWpRApMC7C/XDtekjgDLiJtAUXY
        K/4DaF7hYc7rqlixj7tT58zwnxVxBwaDa5IL+nDgCAu1mqbyx9VMXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a3kdeu05ux3tk8hzlwvtz5jfwejpeegwya04adkc98hyaecj9ecs57t7vt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T04:52:58Z"
  mac: ENC[AES256_GCM,data:g+nfYZ3rBBuvZoBJha8unqeSFuMNxfEwHQEZtQ8qbqHL57wav7T9TRXX2i81tUYRtR9Dk7hJxHSzte58dc2+1kO5ux5+EuuqHpMHQrenaRSNx/p8Eu0hr/1rRvxwCYdgpl9pC+6Msv3kms8MLwXJbGxqai64hs1QSJ+iF8lI2jk=,iv:iyCSD9bhr1GIsT2T3I/ScSrSHjIv05kN2QvdvqBSzNo=,tag:cG1gtrmBRL17PWE7j05N/w==,type:str]
  version: 3.13.1
