---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-dex
  namespace: flux-system
spec:
  path: ./kubernetes/apps/identity/dex/app
  # account for items that are removed from the path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: dex
      namespace: identity
  interval: 30m
  retryInterval: 1m
  timeout: 3m
