---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: networking
spec:
  chart:
    spec:
      chart: portainer
      version: 1.0.40
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
  interval: 15m
  maxHistory: 3
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: ingress-traefik
        hosts:
          - host: &host portainer.techvomit.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: techvomit-xyz-production-tls

    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true

    logs:
      general:
        format: json
        level: DEBUG

    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.20.210
        path: /volume1/k8s/portainer
