---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: 1.0.40
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.20.210
        path: /volume1/k8s/portainer

    ingress:
      enabled: true
      ingressClassName: ingress-traefik
      annotations:
        # External DNS Annotation
        external-dns.alpha.kubernetes.io/hostname: portainer.techvomit.xyz
      hosts:
        - host: &host portainer.techvomit.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: techvomit-xyz-production-tls
