---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rancher
      # reconcileStrategy: ChartVersion
      version: 2.7.5-rc1
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  interval: 15m
  values:
    addLocal: "true"
    additionalTrustedCAs: false
    antiAffinity: preferred
    auditLog:
      destination: sidecar
      hostPath: /var/log/rancher/audit/
      image:
        pullPolicy: IfNotPresent
        repository: rancher/mirrored-bci-micro
        tag: 15.4.14.3
      level: 0
      maxAge: 1
      maxBackup: 1
      maxSize: 100
    certmanager:
      version: ""
    customLogos:
      accessMode: ReadWriteOnce
      enabled: false
      size: 1Gi
      volumeKind: persistentVolumeClaim
      volumeSubpaths:
        emberUi: ember
        vueUi: vue
    debug: false
    hostname: rancher.techvomit.xyz

    ingress:
      annotations:
        noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster,.techvomit.xyz
      main:
        enabled: true
        ingressClassName: ingress-traefik
        hosts:
          - host: &host rancher.techvomit.xyz
            paths:
              - path: /
                pathType: Prefix

    postDelete:
      enabled: true
      ignoreTimeoutError: false
      image:
        repository: rancher/shell
        tag: v0.1.18
      namespaceList:
        - cattle-fleet-system
        - cattle-system
        - rancher-operator-system
      timeout: 120
    priorityClassName: rancher-critical
    rancherImage: rancher/rancher
    replicas: 1
    restrictedAdmin: false
    tls: external
    topologyKey: kubernetes.io/hostname
    useBundledSystemChart: false