---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-subdir-external-provisioner
  path: ./kubernetes/apps/home-automation/home-assistant/app
  # account for items that are removed from the path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: home-automation
  interval: 30m
  retryInterval: 1m
  timeout: 3m
