---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-secret
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
  data:
    - secretKey: FRIGATE_FRONT_LEFT_PASSWORD
      remoteRef:
        key: Front Left Camera - Synology Credentials
        property: password
    - secretKey: FRIGATE_FRONT_RIGHT_PASSWORD
      remoteRef:
        key: Front Right Camera - Synology Credentials
        property: password
    - secretKey: FRIGATE_BACK_LEFT_PASSWORD
      remoteRef:
        key: Back Left Camera
        property: password
    - secretKey: FRIGATE_BACK_RIGHT_PASSWORD
      remoteRef:
        key: Back Right Camera
        property: password
    - secretKey: FRIGATE_LIVING_ROOM_PASSWORD
      remoteRef:
        key: Living Room Camera
        property: password
    - secretKey: FRIGATE_GARAGE_PASSWORD
      remoteRef:
        key: Garage Camera
        property: password
    - secretKey: FRIGATE_MQTT_USER
      remoteRef:
        key: mosquitto-secret
        property: MOSQUITTO_MQTT_USERNAME
    - secretKey: FRIGATE_MQTT_PASSWORD
      remoteRef:
        key: mosquitto-secret
        property: MOSQUITTO_MQTT_PASSWORD
