---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  path: ./kubernetes/apps/external-secrets/external-secrets/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: *namespace
  targetNamespace: external-secrets
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets-stores
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: external-secrets
  interval: 10m
  path: ./kubernetes/apps/external-secrets/external-secrets/stores
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: *namespace
  targetNamespace: external-secrets
  timeout: 5m
  wait: true
