---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - dashboards/home-assistant-dashboard.yaml
  - dashboards/ansible-logs-dashboard.yaml
  - dashboards/udmpro-dashboard.yaml
