---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name onepassword-connect
spec:
  staticConfigs:
    - targets:
        - onepassword-connect.external-secrets.svc.cluster.local:8080
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
