---
# Area
- name: area/ansible
  color: "0075ca"
  description: >-
    Changes made to Ansible configurations and scripts

- name: area/docs
  color: "fbca04"
  description: >-
    Changes made in the docs directory

- name: area/github
  color: "72ccf3"
  description: >-
    Changes made to github actions

- name: area/hack-scripts
  color: "fc0356"
  description: >-
    Changes made to scripts in the hack directory

- name: area/kubernetes
  color: "72ccf3"
  description: >-
    Changes made to kubernetes resources

- name: area/magefiles
  color: "6a0572"
  description: >-
    Changes made to magefiles

- name: area/pre-commit
  color: "BC9BE3"
  description: >-
    Changes made to pre-commit hooks

- name: area/terraform
  color: "7c9494"
  description: >-
    Changes made to Terraform configurations

- name: area/go
  color: "7bd7e0"
  description: >-
    Changes made to go resources

# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: broken-links
  color: "7B55D7"
- name: question
  color: "cc317c"
- name: community
  color: "0e8a16"
