---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-syslog
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: vector
      version: 0.36.1
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    role: Stateless-Aggregator
    service:
      type: LoadBalancer
      ports:
        - name: syslog-udp
          port: 514
          protocol: UDP
          targetPort: 514
    env:
      - name: VECTOR_LOG
        value: "debug"
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: "0.0.0.0:8686"
      sources:
        unifi_raw:
          type: socket
          address: "0.0.0.0:514"
          mode: udp
          decoding:
            codec: bytes
      sinks:
        console_debug:
          type: console
          inputs: ["unifi_raw"]
          encoding:
            codec: json
        to_loki:
          type: loki
          inputs: ["unifi_raw"]
          endpoint: "http://loki-gateway.observability.svc.cluster.local:80"
          encoding:
            codec: text
          labels:
            source: "unifi"
            device: "udmpro"
            job: "syslog"
