---
keys:
  - &user_flux age130xlnwkp6ncpwd85pfqh69sr79wreazqyqq5w579w8q59d0j35fqsxsnvy

creation_rules:
  - path_regex: kubernetes/.+\.secret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *user_flux

  - path_regex: kubernetes/.+\.secret(\.sops)?\.env
    key_groups:
      - age:
          - *user_flux

stores:
  yaml:
    indent: 2
