---
keys:
  - &user_flux age1a3kdeu05ux3tk8hzlwvtz5jfwejpeegwya04adkc98hyaecj9ecs57t7vt

creation_rules:
  - path_regex: kubernetes/.+\.secret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *user_flux

  - path_regex: kubernetes/.+\.secret(\.sops)?\.env
    key_groups:
      - age:
          - *user_flux

  - filename_regex: 'age-key\.yaml$'
    age: *user_flux

stores:
  yaml:
    indent: 2
