---
creation_rules:
  - path_regex: kubernetes/.*\.secret(\.sops)?\.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age18z6gsrajdajtnv2h39qxsqd0g264e6c0jht9due6xmhgpe09pg2sqp4fzq

  - path_regex: kubernetes/bootstrap/flux/age-key\.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age18z6gsrajdajtnv2h39qxsqd0g264e6c0jht9due6xmhgpe09pg2sqp4fzq

  - path_regex: kubernetes/.*\.secret(\.sops)?\.env
    key_groups:
      - age:
          - age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta

  - filename_regex: 'age-key\.yaml$'
    age: age18z6gsrajdajtnv2h39qxsqd0g264e6c0jht9due6xmhgpe09pg2sqp4fzq
