---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ares-llm-secret
  namespace: attack-simulation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1h
  target:
    name: ares-llm-secret
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: "DOpenai"
        property: "dreadnode-ares-api-key"
