---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: sliver
      app.kubernetes.io/instance: sliver
namespace: c2
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
