---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sliver
  namespace: c2
  annotations:
    # External DNS Annotations
    external-dns.alpha.kubernetes.io/hostname: sliver.techvomit.xyz
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sliver.techvomit.xyz`) && PathPrefix(`/some/path`)
      kind: Rule
      services:
        - name: sliver
          port: 80
      middlewares:
        - name: check-user-agent
    - match: Host(`sliver.techvomit.xyz`) && PathPrefix(`/another/path`)
      kind: Rule
      services:
        - name: sliver
          port: 80
    - match: Host(`sliver.techvomit.xyz`)
      kind: Rule
      services:
        - name: sliver
          port: 80
      middlewares:
        - name: redirect-to-website
  tls:
    secretName: techvomit-xyz-production-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: check-user-agent
  namespace: c2
spec:
  headers:
    customRequestHeaders:
      User-Agent: "Chrome/5.0 (erm; Windows 11; super legit user agent string)"
