---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sliver.techvomit.xyz
  name: sliver
  namespace: c2
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: sliver
