---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sliver
  namespace: c2
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: redirect-web-to-443@internal
spec:
  ingressClassName: ingress-traefik
  rules:
    - host: &host sliver.techvomit.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sliver
                port:
                  number: 80
  tls:
    - hosts:
        - *host
      secretName: techvomit-xyz-production-tls
