---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sliver
  namespace: c2
spec:
  ingressClassName: ingress-traefik
  rules:
    - host: sliver.techvomit.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sliver
                port:
                  number: 8443
  tls:
    - hosts:
        - sliver.techvomit.xyz
      secretName: techvomit-xyz-production-tls
