---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # External DNS Annotations
    external-dns.alpha.kubernetes.io/hostname: sliver.techvomit.xyz
  name: sliver
  namespace: c2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: sliver-grpc
      port: 32736
      targetPort: 32736
      protocol: TCP
  selector:
    app: sliver
