---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sliver.techvomit.xyz
  name: sliver
  namespace: c2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 44344
      targetPort: 44344
      protocol: TCP
  selector:
    app: sliver
