---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  chart:
    spec:
      chart: rancher
      # reconcileStrategy: ChartVersion
      version: 2.7.3
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    additionalArguments:
      - --log.level=DEBUG
    env:
      TZ: "America/Denver"
    additionalTrustedCAs: false
    antiAffinity: preferred
    topologyKey: kubernetes.io/hostname
    auditLog:
      destination: sidecar
      hostPath: /var/log/rancher/audit/
      level: 0
      maxAge: 1
      maxBackup: 1
      maxSize: 100
      image:
        repository: "rancher/mirrored-bci-micro"
        tag: 15.4.14.3
        pullPolicy: "IfNotPresent"
    addLocal: "true"
    debug: false
    restrictedAdmin: false
    hostname: rancher.techvomit.xyz
    deployment:
      replicas: 1
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: &host rancher.techvomit.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: techvomit-xyz-production-tls
    replicas: 1
    priorityClassName: rancher-critical
    tls: external
    useBundledSystemChart: false
    certmanager:
      version: ""
    customLogos:
      enabled: false
      volumeSubpaths:
        emberUi: "ember"
        vueUi: "vue"
      volumeKind: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
    postDelete:
      enabled: true
      image:
        repository: rancher/shell
        tag: v0.1.18
      namespaceList:
        - cattle-fleet-system
        - cattle-system
        - rancher-operator-system
      timeout: 120
      ignoreTimeoutError: false
