---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: atomic-red-team
  namespace: flux-system
spec:
  path: ./kubernetes/apps/attack-simulation/atomic-red-team/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true # account for items that are removed from the path
  sourceRef:
    kind: GitRepository
    name: flux-system
