---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: nfs-subdir-external-provisioner
    - name: ingress-traefik
  path: ./kubernetes/apps/security/authentik/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
