---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sliver
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 5m
  path: ./kubernetes/apps/c2/sliver/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: *namespace
  targetNamespace: c2
  timeout: 10m
