---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.18
            command: ["/bin/sh", "-c"]
            args:
              [
                "cp /tmp/secret/* /mosquitto/external_config/ && mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd",
              ]
        containers:
          app:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.18
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 16Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mosquitto.techvomit.xyz
        ports:
          mqtt:
            port: 1883
    ingress:
      app:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mosquitto.techvomit.xyz
        hosts:
          - host: mosquitto.techvomit.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: mosquitto
                  port: 1883
    persistence:
      config:
        type: nfs
        server: 192.168.20.210
        path: /volume1/k8s/mosquitto
        globalMounts:
          - path: /mosquitto/config
      config-file:
        type: configMap
        name: mosquitto-configmap
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
      secret-file:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          mosquitto:
            init-config:
              - path: /tmp/secret
      external-config:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
    env:
      TZ: "America/Denver"
    securityContext:
      runAsUser: 1883
      runAsGroup: 1883
    logs:
      general:
        format: json
        level: DEBUG
