---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.18
            command: ["/bin/sh", "-c"]
            args:
              - |
                touch /mosquitto/config/passwd && \
                cp /tmp/secret/* /mosquitto/config/ && \
                mosquitto_passwd -U /mosquitto/config/passwd
        containers:
          app:
            image:
              repository: docker.io/library/eclipse-mosquitto
              tag: 2.0.18
            command: [mosquitto, -c, /mosquitto/config/mosquitto.conf]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 16Mi
    service:
      app:
        controller: mosquitto
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: mosquitto.techvomit.xyz
        ports:
          mqtt:
            port: 1883
          mqtts:
            port: 8883
    env:
      TZ: "America/Denver"
    logs:
      general:
        format: json
        level: DEBUG
    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf
      data:
        enabled: true
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 64Mi
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/data
      auth:
        enabled: true
        type: secret
        name: mosquitto-secret
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/passwd
                subPath: passwd
              - path: /mosquitto/config/acl
                subPath: acl
      tls-certs:
        type: secret
        name: techvomit-xyz-production-tls
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/certs/tls.crt
                subPath: tls.crt
              - path: /mosquitto/certs/tls.key
                subPath: tls.key
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            per_listener_settings false
            listener 1883
            listener 8883
            allow_anonymous false
            persistence true
            persistence_location /mosquitto/data
            autosave_interval 1800
            # SSL/TLS settings
            certfile /mosquitto/certs/tls.crt
            keyfile /mosquitto/certs/tls.key
            log_dest stderr
            log_type error
            log_type warning

            password_file /mosquitto/config/passwd
            acl_file /mosquitto/config/acl
