---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 2h
  url: oci://ghcr.io/external-secrets/charts/external-secrets
  ref:
    semver: ">=0.20.0"
