---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubed
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kubed
      version: 0.13.2
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
  interval: 15m
  maxHistory: 3
  install:
    timeout: 10m
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  uninstall:
    keepHistory: false
