---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nfs-subdir-external-provisioner
  namespace: &namespace flux-system
spec:
  path: ./kubernetes/apps/kube-system/nfs-subdir-external-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: *namespace
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
