---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: ollama
namespace: inference
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./middleware.yaml
