---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-guacamole
  namespace: flux-system
spec:
  path: ./kubernetes/apps/guacamole/guacamole/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  # account for items that are removed from the path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
