---
apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: observability
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.16
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 1514
      protocol: UDP
