---
apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: observability
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 1514
      protocol: UDP
