---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: Cloudflare
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_API_KEY: "{{ .CLOUDFLARE_API_KEY }}"
  dataFrom:
    - extract:
        key: "Cloudflare"
