---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-key-secret
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_API_KEY: "{{ .CLOUDFLARE_API_KEY }}"
  dataFrom:
    - extract:
        key: "Cloudflare API Credentials"
