---
##### Production #####
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jayson.e.grace@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    # Enable the DNS-01 challenge provider
    solvers:
      - dns01:
          cloudflare:
            email: jayson.e.grace@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: CLOUDFLARE_API_KEY
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techvomit-xyz-production
  namespace: cert-manager
spec:
  secretName: techvomit-xyz-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "techvomit.xyz"
    - "*.techvomit.xyz"
##### Staging #####
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: jayson.e.grace@gmail.com
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     # Enable the DNS-01 challenge provider
#     solvers:
#       - dns01:
#           cloudflare:
#             email: jayson.e.grace@gmail.com
#             apiKeySecretRef:
#               name: cloudflare-api-key-secret
#               key: apiKey

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: techvomit-xyz-staging
#   namespace: cert-manager
# spec:
#   secretName: techvomit-xyz-staging-tls
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   dnsNames:
#     - "techvomit.xyz"
#     - "*.techvomit.xyz"
