---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evilginx2-ingress
  namespace: evilginx2
spec:
  rules:
    - host: &host evilginx2.techvomit.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: evilginx2-service
                port:
                  number: 443
  tls:
    - hosts:
        - *host
