---
apiVersion: v1
kind: Service
metadata:
  name: evilginx2
  namespace: evilginx2
spec:
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
  selector:
    app: evilginx2
