---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-portainer
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/portainer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: portainer
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
