---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nas-nfs
  namespace: observability
spec:
  interval: 30s
  scrapeTimeout: 10s
  module: tcp_connect
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
        - 192.168.20.210:2049
      labels:
        target: synology-nas
        port_role: nfs
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: kube-api-vip
  namespace: observability
spec:
  interval: 30s
  scrapeTimeout: 10s
  module: tcp_connect
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
        - 192.168.20.150:6443
      labels:
        target: kube-api-vip
        port_role: kubernetes-api
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: signal-bridge
  namespace: observability
spec:
  interval: 60s
  scrapeTimeout: 10s
  module: tcp_connect
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
        - 192.168.20.45:8080
      labels:
        target: signal-bridge
        port_role: alert-delivery
