---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  targetNamespace: home-automation
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: external-secrets-stores
  path: ./kubernetes/apps/home-automation/mosquitto/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
