---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actions-runner-controller-cache
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: &name actions-runner-controller
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-client
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 8Gi
