---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy: false
  # https://github.com/redhat-developer/vscode-yaml/issues/433#issuecomment-1235681987
  comments:
    min-spaces-from-content: 1
