---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
  namespace: home-automation
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: grocy
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      grocy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/grocy
              tag: 4.2.0
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Denver"
              GROCY_CULTURE: "en"
              GROCY_CURRENCY: "USD"
              GROCY_MODE: production
              PUID: "1000"
              PGID: "1000"
              # PHP Performance optimizations
              PHP_MEMORY_LIMIT: "512M"
              PHP_MAX_EXECUTION_TIME: "60"
              PHP_OPCACHE_ENABLE: "1"
              PHP_OPCACHE_MEMORY_CONSUMPTION: "128"
              PHP_OPCACHE_MAX_ACCELERATED_FILES: "10000"
              PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
              # SQLite optimizations
              GROCY_DATABASE_PRAGMA_JOURNAL_MODE: "WAL"
              GROCY_DATABASE_PRAGMA_SYNCHRONOUS: "NORMAL"
              GROCY_DATABASE_PRAGMA_CACHE_SIZE: "-64000"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
    service:
      app:
        controller: grocy
        ports:
          http:
            port: 80
    ingress:
      app:
        className: ingress-traefik
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grocy.techvomit.xyz
        hosts:
          - host: &host grocy.techvomit.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: techvomit-xyz-production-tls
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: nfs-client
        globalMounts:
          - path: /config
      viewcache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 256Mi
        globalMounts:
          - path: /config/data/viewcache
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 128Mi
        globalMounts:
          - path: /tmp
