---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
  namespace: home-automation
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: grocy
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      grocy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: linuxserver/grocy
              tag: 4.0.3
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Denver"
              GROCY_CULTURE: "en"
              GROCY_CURRENCY: "USD"
              GROCY_MODE: production
              PUID: "1000"
              PGID: "1000"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: grocy
        ports:
          http:
            port: 80
    ingress:
      app:
        className: ingress-traefik
        annotations:
          external-dns.alpha.kubernetes.io/hostname: grocy.techvomit.xyz
        hosts:
          - host: &host grocy.techvomit.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: techvomit-xyz-production-tls
    logs:
      general:
        format: json
        level: DEBUG
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: nfs-client
        globalMounts:
          - path: /config
      viewcache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config/data/viewcache
