---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: grocy
      app.kubernetes.io/instance: grocy
namespace: home-automation
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
