---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mysql
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/mysql/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
