---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: woe
  namespace: actions-runner-system
spec:
  template:
    spec:
      # The repo that this runner will be assigned to.
      repository: cowdogmoo/walls-of-excellence
      imagePullPolicy: IfNotPresent
      labels: ["self-hosted"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: actions-runner-controller-cache

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: woe-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: woe
  minReplicas: 1
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        # The repo that this runner will be assigned to.
        - cowdogmoo/walls-of-excellence
