---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vector
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/observability/vector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: observability
  timeout: 5m
  wait: false
