---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Skip
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
        chunk_idle_period: 1h
        chunk_target_size: 2621440
        max_chunk_age: 1h
      limits_config:
        retention_period: 14d
        retention_delete_delay: 2h
        reject_old_samples: true
        reject_old_samples_max_age: 336h # 14 days - match retention
        unordered_writes: true
        # Performance optimizations
        max_query_parallelism: 32
        split_queries_by_interval: 15m
        max_cache_freshness_per_query: 10m
        max_entries_limit_per_query: 5000
        query_timeout: 5m
        max_concurrent_tail_requests: 10
      server:
        grpc_server_max_recv_msg_size: 10485760 # 10 MiB
        grpc_server_max_send_msg_size: 10485760 # 10 MiB
        log_level: info
        http_server_read_timeout: 5m
        http_server_write_timeout: 5m
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      structuredConfig:
        query_range:
          align_queries_with_step: true
          max_retries: 5
          parallelise_shardable_queries: true
          cache_results: true
        frontend:
          log_queries_longer_than: 5s
          compress_responses: true
          max_outstanding_per_tenant: 2048
        querier:
          max_concurrent: 20
          query_ingesters_within: 3h
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /rules/fake
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: nfs-client
        size: 50Gi
      resources:
        requests:
          cpu: 2
          memory: 4Gi
        limits:
          cpu: 4
          memory: 8Gi
      extraEnv:
        - name: GOGC
          value: "80"

    gateway:
      enabled: true
      replicas: 1
      verboseLogging: true
      nginxConfig:
        httpSnippet: |
          upstream loki {
            server loki:3100;
            keepalive 15;
          }
        serverSnippet: |
          client_body_buffer_size 100M;
          client_max_body_size 100M;
          proxy_read_timeout 300s;
          proxy_connect_timeout 300s;
          proxy_send_timeout 300s;

          location = /ready {
            proxy_pass http://loki/ready;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_connect_timeout 1s;
          }

          location / {
            proxy_pass http://loki$request_uri;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
          }
      ingress:
        enabled: true
        ingressClassName: ingress-traefik
        hosts:
          - host: &host loki.techvomit.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.10
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake
