---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.41.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      commonConfig:
        replication_factor: 1
      auth_enabled: false
      storage:
        type: filesystem
      limits_config:
        retention_period: 14d
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 32
        per_stream_rate_limit: 8MB
        per_stream_rate_limit_burst: 16MB
      compactor:
        retention_enabled: true
        working_directory: /var/loki/boltdb-shipper-compactor
        shared_store: filesystem
        compaction_interval: 10m
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
      ruler:
        enable_api: true
        enable_alertmanager_v2: true
        alertmanager_url: http://kube-prometheus-stack-alertmanager.observability:9093
      query_scheduler:
        max_outstanding_requests_per_tenant: 2048
      querier:
        max_concurrent: 2048
      frontend:
        max_outstanding_per_tenant: 2048
    monitoring:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Loki
      serviceMonitor:
        enabled: true
        metricsInstance:
          enabled: true
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
    read:
      persistence:
        size: 10Gi
        storageClass: nfs-client
    write:
      persistence:
        size: 10Gi
        storageClass: nfs-client
    backend:
      persistence:
        size: 10Gi
        storageClass: nfs-client
