---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.35.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 14d
        allow_structured_metadata: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 32
        per_stream_rate_limit: "8MB"
        per_stream_rate_limit_burst: "16MB"

    test:
      enabled: false

    deploymentMode: "SingleBinary<->SimpleScalable"
    singleBinary:
      enabled: true
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: nfs-client
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1Gi

    scalable:
      enabled: false

    gateway:
      enabled: true
      replicas: 1
      verboseLogging: true

    monitoring:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Loki
      serviceMonitor:
        enabled: true
        metricsInstance:
          enabled: true
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false

    lokiCanary:
      enabled: false

    chunksCache:
      enabled: false
