---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.41.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      limits_config:
        retention_period: 14d
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 32
        per_stream_rate_limit: 8MB
        per_stream_rate_limit_burst: 16MB

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: nfs-client

    service:
      type: ClusterIP
      externalTrafficPolicy: Cluster

    ingress:
      enabled: true
      ingressClassName: ingress-traefik
      annotations:
        external-dns.alpha.kubernetes.io/hostname: loki.techvomit.xyz
      hosts:
        - host: &host loki.techvomit.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: techvomit-xyz-production-tls

    monitoring:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Loki
      serviceMonitor:
        enabled: true
        metricsInstance:
          enabled: true
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
