---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.38.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
        grpc_server_max_recv_msg_size: 10485760 # 10 MiB
        grpc_server_max_send_msg_size: 10485760 # 10 MiB
      commonConfig:
        replication_factor: 1
        path_prefix: /var/loki
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      compactor:
        working_directory: /var/loki/compactor
        retention_enabled: true
        delete_request_store: filesystem
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 14d

    test:
      enabled: false

    singleBinary:
      enabled: true
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: nfs-client
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1Gi
      extraArgs:
        - -config.expand-env=true
      readinessProbe:
        httpGet:
          path: /ready
          port: http-metrics
        initialDelaySeconds: 60
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 5

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    gateway:
      enabled: true
      replicas: 1
      verboseLogging: true
      ingress:
        enabled: true
        ingressClassName: ingress-traefik
        hosts:
          - host: &host loki.techvomit.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    monitoring:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Loki
      serviceMonitor:
        enabled: true
        metricsInstance:
          enabled: true
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false

    lokiCanary:
      enabled: false

    resultsCache:
      enabled: false

    chunksCache:
      enabled: false

    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 1.30.10@sha256:dd3b1f0c4e6b4512b2deb50c58acf65fd0f0927120a59a95eec854d32a6c9ce3
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake
