---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-gh-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flux-gh-token
    template:
      engineVersion: v2
      data:
        token: "{{ .FLUX_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: "flux-gh-token"
