---
apiVersion: batch/v1
kind: Job
metadata:
  name: guacamole-admin-init
  namespace: guacamole
  annotations:
    # This ensures the job runs after the deployment is ready
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: guacamole-admin-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: admin-init
          image: postgres:18-alpine
          command:
            - /bin/sh
            - -c
            - |
              # Extract password from guacamole.properties
              echo "Reading database password from guacamole.properties..."
              export PGPASSWORD=$(grep "postgresql-password:" /config/guacamole/guacamole.properties | cut -d' ' -f2)

              if [ -z "$PGPASSWORD" ]; then
                echo "ERROR: Could not read postgresql-password from guacamole.properties"
                exit 1
              fi

              # Wait for Guacamole PostgreSQL to be ready
              echo "Waiting for Guacamole PostgreSQL to be ready..."
              until psql -h guacamole -U guacamole -d guacamole_db -c '\q' 2>/dev/null; do
                echo "PostgreSQL not ready, waiting..."
                sleep 5
              done

              echo "PostgreSQL is ready. Setting up admin users..."

              # Create SSO user entities if not exist and grant admin permissions
              # Handle both email and username formats

              # First, create the entities
              psql -h guacamole -U guacamole -d guacamole_db <<'EOSQL'
              INSERT INTO guacamole_entity (name, type)
              VALUES
                  ('jayson.e.grace@gmail.com', 'USER'),
                  ('jayson', 'USER')
              ON CONFLICT (name, type) DO NOTHING;
              EOSQL

              # Then grant permissions to each user
              for username in "jayson.e.grace@gmail.com" "jayson"; do
                echo "Granting admin permissions to: $username"

                psql -h guacamole -U guacamole -d guacamole_db <<EOSQL
              -- Get entity_id and create user record if needed
              INSERT INTO guacamole_user (entity_id, password_hash, password_salt, password_date)
              SELECT entity_id, E'\\\\x', E'\\\\x', NOW()
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id) DO NOTHING;

              -- Grant ALL system permissions
              INSERT INTO guacamole_system_permission (entity_id, permission)
              SELECT entity_id, 'CREATE_CONNECTION'
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id, permission) DO NOTHING;

              INSERT INTO guacamole_system_permission (entity_id, permission)
              SELECT entity_id, 'CREATE_CONNECTION_GROUP'
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id, permission) DO NOTHING;

              INSERT INTO guacamole_system_permission (entity_id, permission)
              SELECT entity_id, 'CREATE_SHARING_PROFILE'
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id, permission) DO NOTHING;

              INSERT INTO guacamole_system_permission (entity_id, permission)
              SELECT entity_id, 'CREATE_USER'
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id, permission) DO NOTHING;

              INSERT INTO guacamole_system_permission (entity_id, permission)
              SELECT entity_id, 'CREATE_USER_GROUP'
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id, permission) DO NOTHING;

              INSERT INTO guacamole_system_permission (entity_id, permission)
              SELECT entity_id, 'ADMINISTER'
              FROM guacamole_entity
              WHERE name = '$username' AND type = 'USER'
              ON CONFLICT (entity_id, permission) DO NOTHING;
              EOSQL
              done

              echo "Admin user setup complete!"
          volumeMounts:
            - mountPath: /config
              name: guacamole-pvc
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
      volumes:
        - name: guacamole-pvc
          persistentVolumeClaim:
            claimName: guacamole-pvc
