---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # External DNS Annotations
    external-dns.alpha.kubernetes.io/hostname: guacamole.techvomit.xyz
  name: guacamole
  namespace: guacamole
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: guacamole
