---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops
rules:
  - apiGroups: [""]
    resources: [users, groups]
    verbs: [impersonate]
  - nonResourceURLs:
      - /api
      - /api/*
      - /apis
      - /apis/*
    verbs:
      - get
