---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: weave-gitops-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: weave-gitops-secret
    template:
      engineVersion: v2
      data:
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: "weave-gitops-secret"
