---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-subdir-external-provisioner
  path: ./kubernetes/apps/networking/ingress-traefik/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
