---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-subdir-external-provisioner
  path: ./kubernetes/apps/networking/ingress-traefik/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  # account for items that are removed from the path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
