---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nfs-subdir-external-provisioner
    - name: cluster-apps-cert-manager
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-external-dns
  path: ./kubernetes/apps/networking/ingress-traefik/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  # account for items that are removed from the path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
