---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runzero-explorer
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/runzero-explorer/app
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  prune: true # account for items that are removed from the path
  sourceRef:
    kind: GitRepository
    name: flux-system
