---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    global:
      # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
      logLevel: 6
      leaderElection:
        # Override the namespace used to store the ConfigMap for leader election
        namespace: cert-manager
    replicaCount: 3
    dns01RecursiveNameservers: "1.1.1.1:53,9.9.9.9:53"
    dns01RecursiveNameserversOnly: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: observability
    webhook:
      replicaCount: 2
    cainjector:
      replicaCount: 2
