---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  # # renovate: datasource=github-releases depName=cert-manager/cert-manager
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.5.0/cert-manager.crds.yaml
  - helmrelease.yaml
  - prometheusrule.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/part-of: cert-manager
