---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grocy
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nfs-subdir-external-provisioner
  path: ./kubernetes/apps/home-automation/grocy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v2beta1
  #     kind: HelmRelease
  #     name: grocy
  #     namespace: home-automation
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
