---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin-credentials
    template:
      engineVersion: v2
      data:
        GRAFANA_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        GRAFANA_ADMIN_PW: "{{ .GRAFANA_ADMIN_PW }}"
  dataFrom:
    - extract:
        key: "grafana-admin-secret"
