---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: unpoller
      version: 2.11.2-Chart6 # <- This is the correct chart version
      sourceRef:
        kind: HelmRepository
        name: unpoller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: golift/unifi-poller
      tag: v2.11.2

    poller:
      service:
        type: ClusterIP
        port: 9130
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9130"

    prometheus:
      serviceMonitor:
        enabled: true
        interval: 30s
        labels:
          release: kube-prometheus-stack

    config:
      prometheus:
        disable: false
        http_listen: "0.0.0.0:9130"
        report_errors: true

      influxdb:
        disable: true

      unifi:
        dynamic: false
        defaults:
          url: "${UNIFI_URL}"
          user: "${UNIFI_USER}"
          pass: "${UNIFI_PASS}"
          verify_ssl: false
          save_ids: true
          save_events: true
          save_alarms: true
          save_anomalies: true
          save_dpi: true
          save_sites: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    envFrom:
      - secretRef:
          name: unifi-automation-secret
