---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-config-syncer
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/config-syncer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: kubed
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
