---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: hashcat
      app.kubernetes.io/instance: hashcat
namespace: cracking
resources:
  - ./service.yaml
  - ./externalsecret.yaml
