---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runzero-explorer
  namespace: observability
  labels:
    app: runzero-explorer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runzero-explorer
  template:
    metadata:
      labels:
        app: runzero-explorer
    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - runzero-explorer
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: runzero-explorer
          image: ghcr.io/cowdogmoo/runzero-explorer:latest
          imagePullPolicy: Always
          command: ["/opt/runzero/bin/runzero-explorer.bin", "manual"]
          securityContext:
            runAsUser: 0
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
