---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runzero-explorer
  namespace: observability
  labels:
    app: runzero-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runzero-explorer
  template:
    metadata:
      labels:
        app: runzero-explorer
    spec:
      initContainers:
        - name: init-symlink
          image: busybox
          command:
            [
              "/bin/sh",
              "-c",
              "ln -s /opt/runzero/bin/runzero-agent-* /opt/runzero/bin/runzero-agent",
            ]
          volumeMounts:
            - name: runzero-explorer-pvc
              mountPath: /opt/runzero/bin
      containers:
        - name: runzero-explorer
          image: ghcr.io/cowdogmoo/runzero-explorer:latest
          imagePullPolicy: Always
          command: ["/opt/runzero/bin/runzero-agent", "manual"]
          securityContext:
            runAsUser: 0 # Run as root user
            privileged: true # Required for full functionality of runZero scanner
          volumeMounts:
            - name: runzero-explorer-pvc
              mountPath: /opt/runzero/bin
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: runzero-explorer-pvc
          persistentVolumeClaim:
            claimName: runzero-explorer-pvc
