---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mysql-secret
    template:
      engineVersion: v2
      data:
        root-password: "{{ .MYSQL_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: "k8s-woe-db-root-cred"
