---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-red
  namespace: atomic-red
  labels:
    app: atomic-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomic-red
  template:
    metadata:
      labels:
        app: atomic-red
    spec:
      containers:
        - name: atomic-red
          image: ghcr.io/cowdogmoo/atomic-red:latest@sha256:8ca34b43710bf1f2217faea34307a75318a2d3696d86dff6a49e2045f9448454
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
