---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-red
  namespace: atomic-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomic-red
  template:
    metadata:
      labels:
        app: atomic-red
    spec:
      containers:
        - name: atomic-red
          image: ghcr.io/cowdogmoo/invoke-atomicredteam:latest
          command: ["sleep", "3560d"]
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      nodeSelector:
        kubernetes.io/os: linux
