---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-red
  namespace: atomic-red
  labels:
    app: atomic-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomic-red
  template:
    metadata:
      labels:
        app: atomic-red
    spec:
      containers:
        - name: atomic-red
          image: ghcr.io/cowdogmoo/invoke-atomicredteam:latest@sha256:649b7d974f235fc5829493cb43483f4ed8cf39b2d57cf127c1c53bdc7f5c1ca6
          imagePullPolicy: Always
          command: ["sleep", "3560d"]
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
      nodeSelector:
        kubernetes.io/os: linux
