---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
  namespace: monitoring
spec:
  path: ./kubernetes/apps/monitoring/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - kind: HelmRelease
      name: grafana
      namespace: monitoring
  interval: 15m
  retryInterval: 1m
  timeout: 3m
