---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: identity
spec:
  releaseName: dex
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.36.0
    ingress:
      enabled: true
      ingressClassName: ingress-traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # External DNS Annotation
        external-dns.alpha.kubernetes.io/hostname: &host dex.techvomit.xyz
        external-dns.alpha.kubernetes.io/target: ipv4.techvomit.xyz
        external-dns.home.arpa/enabled: "true"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: techvomit-xyz-production-tls
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
    env:
      KUBERNETES_POD_NAMESPACE: identity
    config:
      issuer: https://dex.techvomit.xyz
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID:
              secretKeyRef:
                name: dex-secrets
                key: DEX_OAUTH2_PROXY_CLIENT_ID
            clientSecret:
              secretKeyRef:
                name: dex-secrets
                key: DEX_OAUTH2_PROXY_CLIENT_SECRET
            redirectURI: https://dex.techvomit.xyz/callback
            orgs:
              - name: cowdogmoo
      staticClients:
        - name: oauth2-proxy
          id:
            secretKeyRef:
              name: dex-oauth2-proxy-secrets
              key: DEX_OAUTH2_PROXY_CLIENT_ID
          secret:
            secretKeyRef:
              name: dex-oauth2-proxy-secrets
              key: DEX_OAUTH2_PROXY_CLIENT_SECRET
          redirectURIs:
            - https://auth.techvomit.xyz/oauth2/callback
      storage:
        type: kubernetes
        config:
          inCluster: true
      frontend:
        theme: dark
        issuer: Final Space
        issuerUrl: https://dex.techvomit.xyz
        logoUrl: https://imgur.com/Idzzln9.png
      expiry:
        signingKeys: 6h
        idTokens: 24h
      logger:
        level: debug
        format: json
      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
