---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ttpforge
  namespace: flux-system
spec:
  path: ./kubernetes/apps/attack-simulation/ttpforge/app
  interval: 5m
  retryInterval: 1m
  timeout: 10m
  prune: true # account for items that are removed from the path
  sourceRef:
    kind: GitRepository
    name: flux-system
