---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ttpforge
  namespace: flux-system
spec:
  path: ./kubernetes/apps/attack-simulation/ttpforge/app
  interval: 5m
  retryInterval: 1m
  timeout: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
