---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
  namespace: observability
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      params:
        - name: apcups
          module:
            - apcups
          target: 192.168.20.71
          auth:
            - public_v2
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: instance
