---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - runzero-explorer-deployment.yaml
  - runzero-explorer-service.yaml
  - runzero-explorer-ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: runzero-explorer
      app.kubernetes.io/instance: runzero-explorer
