---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: kube-system
spec:
  interval: 10m
  url: https://emberstack.github.io/helm-charts
  timeout: 3m
