---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nfs-subdir-external-provisioner
    - name: cluster-apps-cert-manager
    - name: cluster-apps-cert-manager-issuers
  path: ./kubernetes/apps/monitoring/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
  interval: 15m
  retryInterval: 1m
  timeout: 5m
