---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # External DNS Annotations
    external-dns.alpha.kubernetes.io/hostname: atomic-red-team.techvomit.xyz
  name: atomic-red-team
  namespace: attack-simulation
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: atomic-red-team
