---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atomic-red-team
  namespace: attack-simulation
spec:
  ingressClassName: ingress-traefik
  rules:
    - host: &host atomic-red-team.techvomit.xyz
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: atomic-red-team
                port:
                  number: 80
            path: /
  tls:
    - hosts:
        - *host
      secretName: techvomit-xyz-production-tls
