---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-red-team
  namespace: attack-simulation
  labels:
    app: atomic-red-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atomic-red-team
  template:
    metadata:
      labels:
        app: atomic-red-team
    spec:
      containers:
        - name: atomic-red-team
          image: ghcr.io/l50/atomic-red-team:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
