---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atomic-red-team
  namespace: attack-simulation
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: atomic-red-team
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      atomic-red-team:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/l50/atomic-red-team
              tag: latest
            command:
              - /bin/bash
              - -ec
              - while :; do echo '.'; sleep 5; done
            env:
              # -- Set the container timezone
              TZ: "America/Denver"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 4096Mi

    pod:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    logs:
      general:
        format: json
        level: DEBUG
