---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: atomic-red-team
      app.kubernetes.io/instance: atomic-red-team
namespace: attack-simulation
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
